import { MuscleGroup } from './types';

export const MUSCLE_GROUPS: MuscleGroup[] = [
  'Chest', 'Back', 'Shoulders', 'Legs', 'Biceps', 'Triceps',
];

export const EXERCISES: Record<MuscleGroup, string[]> = {
  Chest: [
    'Bench Press',
    'Incline Bench Press',
    'Dumbbell Press',
    'Incline Dumbbell Press',
    'Dumbbell Fly',
    'Incline Dumbbell Fly',
    'Cable Fly',
    'Cable Press',
    'Chest Press Machine',
    'Fly Machine',
    'Dumbbell Chest Raises',
    'Cable Chest Raises',
  ],
  Back: [
    'Pull-up',
    'Lat Pulldown',
    'Pulldown Machine',
    'Seated Cable Row',
    'Row Machine',
    'Single-arm Dumbbell Row',
    'Barbell Row',
    'Incline Dumbbell Row',
    'Landmine Row',
  ],
  Shoulders: [
    'Dumbbell Shoulder Press',
    'Shoulder Press Machine',
    'Arnold Press',
    'Lateral Raise',
    'Front Raise',
    'Rear Delt Fly',
    'Face Pull',
    'Dumbbell Shrugs',
    'Cable Shrugs',
  ],
  Legs: [
    'Barbell Squat',
    'Goblet Squat',
    'Bulgarian Split Squats',
    'Leg Press',
    'Romanian Deadlift',
    'Leg Extension',
    'Leg Curl',
    'Hip Thrust',
    'Lunges',
    'Calf Raise',
  ],
  Biceps: [
    'Barbell Curl',
    'Dumbbell Curl',
    'Hammer Curl',
    'Incline Curl',
    'Preacher Curl',
    'Concentration Curl',
    'Cable Curl',
    'Curl Machine',
  ],
  Triceps: [
    'Overhead Tricep Extension',
    'Overhead Cable Extensions',
    'Skull Crusher',
    'Close-grip Bench Press',
    'Pushdown Machine',
    'Cable Pushdown',
    'Dumbbell Kickbacks',
  ],
};
